### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ghost** [TaranVH/LOGOS#4]
This is what it says on your repo description:

![image](https://user-images.githubusercontent.com/14107316/46260680-02e44480-c4e1-11e8-9b6a-a9f83e51d807.png)

Guessing you meant collected instead of "vollected". :D

**Comment by jbruchon** [comment]
I noticed this too. I am also quite the avid vollector.

**Comment by willtheorangeguy** [comment]
This issue can be closed because the README has been fixed! Well spotted though 👍
